lazy val root = (project in file("."))
  .aggregate(tweetPublisher, batching, streaming, common)

lazy val tweetPublisher = (project in file("tweet-publisher"))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings)
  .settings(Settings.default("2.11.12"))
  .settings(libraryDependencies ++= Dependencies.mainPublisher)
  .settings(libraryDependencies ++= Dependencies.unitTestsPublisher)
  .settings(libraryDependencies ++= Dependencies.itTestsPublisher)

lazy val batching = (project in file("batching"))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings)
  .settings(Settings.default("2.11.12"))
  .settings(libraryDependencies ++= Dependencies.mainBatching)
  .settings(libraryDependencies ++= Dependencies.unitTestsBatching)
  .settings(libraryDependencies ++= Dependencies.itTestsBatching)
  .settings(
    assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
  )
  .dependsOn(common, tweetPublisher % IntegrationTest)

lazy val streaming = (project in file("streaming"))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings)
  .settings(Settings.default("2.11.12"))
  .settings(libraryDependencies ++= Dependencies.mainStreaming)
  .settings(libraryDependencies ++= Dependencies.unitTestsBatching)
  .settings(libraryDependencies ++= Dependencies.itTestsBatching)
  .settings(
    assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
  )
  .dependsOn(common, tweetPublisher % IntegrationTest)

lazy val common = (project in file("common"))
  .settings(Settings.default("2.11.12"))
  .settings(libraryDependencies ++= Dependencies.common)
