lazy val root = (project in file("."))
  .configs(IntegrationTest)
  .settings(Defaults.itSettings)
  .settings(Settings.default)
  .settings(libraryDependencies ++= Dependencies.main)
  .settings(libraryDependencies ++= Dependencies.unitTests)
  .settings(libraryDependencies ++= Dependencies.itTests)
